name: Deploy Infrastructure ğŸ› ï¸

on: workflow_dispatch

jobs:
    deploy:
        name: Execute scripts
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v5
